name: chemical_viewer
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_inappbrowser: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/j2s/
    - assets/j2s/J/
    - assets/j2s/J/adapter/
    - assets/j2s/J/adapter/readers/
    - assets/j2s/J/adapter/readers/aflow/
    - assets/j2s/J/adapter/readers/cif/
    - assets/j2s/J/adapter/readers/molxyz/
    - assets/j2s/J/adapter/readers/more/
    - assets/j2s/J/adapter/readers/pdb/
    - assets/j2s/J/adapter/readers/pymol/
    - assets/j2s/J/adapter/readers/quantum/
    - assets/j2s/J/adapter/readers/simple/
    - assets/j2s/J/adapter/readers/xml/
    - assets/j2s/J/adapter/readers/xtal/
    - assets/j2s/J/adapter/smarter/
    - assets/j2s/J/api/
    - assets/j2s/J/appletjs/
    - assets/j2s/J/atomdata/
    - assets/j2s/J/awtjs/
    - assets/j2s/J/awtjs2d/
    - assets/j2s/J/bspt/
    - assets/j2s/J/c/
    - assets/j2s/J/console/
    - assets/j2s/J/consolejs/
    - assets/j2s/J/dssx/
    - assets/j2s/J/export/
    - assets/j2s/J/g3d/
    - assets/j2s/J/geodesic/
    - assets/j2s/J/i18n/
    - assets/j2s/J/image/
    - assets/j2s/J/io/
    - assets/j2s/J/jsv/
    - assets/j2s/J/jvxl/
    - assets/j2s/J/jvxl/api/
    - assets/j2s/J/jvxl/calc/
    - assets/j2s/J/jvxl/data/
    - assets/j2s/J/jvxl/readers/
    - assets/j2s/J/modelkit/
    - assets/j2s/J/modelkit/images/
    - assets/j2s/J/navigate/
    - assets/j2s/J/popup/
    - assets/j2s/J/quantum/
    - assets/j2s/J/render/
    - assets/j2s/J/renderbio/
    - assets/j2s/J/rendercgo/
    - assets/j2s/J/renderspecial/
    - assets/j2s/J/rendersurface/
    - assets/j2s/J/shape/
    - assets/j2s/J/shapebio/
    - assets/j2s/J/shapecgo/
    - assets/j2s/J/shapespecial/
    - assets/j2s/J/shapesurface/
    - assets/j2s/J/thread/
    - assets/j2s/JM/
    - assets/j2s/JM/FF/
    - assets/j2s/JM/FF/data/
    - assets/j2s/JS/
    - assets/j2s/JSV/
    - assets/j2s/JSV/api/
    - assets/j2s/JSV/app/
    - assets/j2s/JSV/appletjs/
    - assets/j2s/JSV/common/
    - assets/j2s/JSV/dialog/
    - assets/j2s/JSV/exception/
    - assets/j2s/JSV/export/
    - assets/j2s/JSV/export/resources/
    - assets/j2s/JSV/js2d/
    - assets/j2s/JSV/popup/
    - assets/j2s/JSV/source/
    - assets/j2s/JSV/tree/
    - assets/j2s/JU/
    - assets/j2s/JV/
    - assets/j2s/JV/binding/
    - assets/j2s/core/
    - assets/j2s/img/
    - assets/j2s/java/
    - assets/j2s/java/awt/
    - assets/j2s/java/awt/event/
    - assets/j2s/java/io/
    - assets/j2s/java/lang/
    - assets/j2s/java/lang/reflect/
    - assets/j2s/java/net/
    - assets/j2s/java/text/
    - assets/j2s/java/util/
    - assets/j2s/java/util/regex/
    - assets/j2s/java/util/zip/
    - assets/j2s/javajs/
    - assets/j2s/javajs/api/
    - assets/j2s/javajs/awt/
    - assets/j2s/javajs/awt/event/
    - assets/j2s/javajs/export/
    - assets/j2s/javajs/img/
    - assets/j2s/javajs/swing/
