name: chemical_viewer
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_inappbrowser: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/j2s/img/
    - assets/j2s/core/
    - assets/j2s/J/adapter/readers/cif
    - assets/j2s/J/render/
    - assets/j2s/J/shape/
    - assets/j2s/javajs/api/
    - assets/j2s/JU/
